export interface AuthEnvironment {
  AUTH_AZURE_ENTERPRISE_APPLICATION_ID: string;
  AUTH_AZURE_APP_REGISTRATION_CLIENT_SECRET_VALUE: string;
  AUTH_AZURE_APP_REGISTRATION_DIRECTORY_TENANT_ID: string;
  AUTH_SECRET: string;
}
